name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake ninja-build nvidia-cuda-toolkit
      - name: Configure
        run: cmake -S . -B build -G "Unix Makefiles"
      - name: Build
        run: cmake --build build -j $(nproc)
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
